<?php

use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_post_render().
 */
function umdlib_fcrepo_solr_helper_views_post_render($view) {
  $field_name = null;
  if ($view->id() == 'fcrepo_detail_display' && count($view->result) > 0) {
    $field_name = 'object__title__display';
  }

  if ($view->id() == 'scores_details' && count($view->result) > 0) {
    $field_name = 'title';
  }

  if ($view->id() == 'plant_patents_detail' && count($view->result) > 0) {
    $field_name = 'display_title';
  }

  if ($view->id() == 'maryland_maps_detail' && count($view->result) > 0) {
    $field_name = 'title';
  }

  if (empty($field_name)) {
    return;
  }

  $results = $view->result[0];
  if (empty($results)) {
    return;
  }

  $d_field = $results->_item->getField($field_name);
  if (!empty($d_field)) {
    $d_title = $d_field->getValues();
  }

  if (!empty($d_title) && !empty($d_title[0])) {
    $new_title = $d_title[0];
    if (str_contains($new_title, '[@ja')) {
      $t_array = [];
      foreach ($d_title as $t) {
        $split = explode("]", $t);
        if (count($split) > 0) {
          $key = str_replace("[@", '', $split[0]);
          $t_array[$key] = $split[1];
          if (!empty($t_array['ja'] && $t_array['ja-Latn'])) {
            $new_title = $t_array['ja'] . " (" . $t_array['ja-Latn'] . ")";
          }
        }
      }
    }
    $view->setTitle($new_title);
    $route = \Drupal::routeMatch()->getCurrentRouteMatch()->getRouteObject();
    $route->setDefault('_title_callback', function() use ($new_title) {
      return $new_title;
    });
  }
}
